package models

import (
	"time"
)

type Session struct {
	ID              int       `json:"id"`              // The ID, will be automatically generated by the database
	Hours           int       `json:"hours"`           // The number of hours for the session
	CourtID         int       `json:"courtid"`         // The ID of the court, a foreign key reference
	ShuttleFee      float64   `json:"shuttlefee"`      // The shuttle fee
	HowManyCourts   int       `json:"howmanycourts"`   // The number of courts used
	HowManyShuttles int       `json:"howmanyshuttles"` // The number of shuttles used
	Date            time.Time `json:"date"`            // The date of the session
}
